apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-kubernetes

spec:
  replicas: 5
  selector:
    matchLabels:
      app: inventory-kubernetes
  template:
    metadata:
      labels:
        app: inventory-kubernetes

    spec:
      containers:
        - name: inventory-kubernetes
          image: jp.icr.io/ramyanamespace/inventory-kubernetes
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP